name = "ParametricFixedPoint"
uuid = "cf6f1fb3-1906-4e32-ac00-2438f5f6928e"
authors = ["Pablo San-Jose <lekand@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
SIAMFANLEquations = "084e46ad-d928-497d-ad5e-07fa361a48c4"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
